---
- name: Configure Mayan
  hosts: edms
  become: true
  become_method: sudo
  roles:
    - role: common
    - role: postgres
      postgresql_version: 9.4
    - role: redis
    - role: mayan
    # - role: nginx
  tasks:
    - name: install postgres client dependencies
      apt: >
        pkg=libpq-dev
        state=latest
        update_cache=yes
        cache_valid_time={{ apt_cache_valid_time }}
        force=yes

    - name: create mayan database
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_db: >
        name=mayan
        encoding='UTF-8'
        lc_collate='en_US.UTF-8'
        lc_ctype='en_US.UTF-8'
        template='template0'
      register: mayan_db_create

    - name: create mayan user
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_user: >
        db=mayan
        name=mayan
        password={{ mayan_db_password }}
      when: mayan_db_create.changed

    - name: apply privileges for mayan user
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_privs: >
        db=mayan
        type=schema
        objs=public
        privs=ALL
        roles=mayan
      when: mayan_db_create.changed

    - name: Install Mayan configuration
      become: yes
      become_user: "{{ mayan_user }}"
      template: >
        src=mayan/config.yml.j2
        dest={{ mayan_dest_dir}}/mayan-edms/media/config.yml

    - name: Mayan Initialsetup
      become: yes
      become_user: "{{ mayan_user }}"
      shell: >
        MAYAN_DATABASE_ENGINE=django.db.backends.postgresql 
        MAYAN_DATABASE_NAME=mayan 
        MAYAN_DATABASE_PASSWORD={{ mayan_db_password }} 
        MAYAN_DATABASE_USER=mayan 
        MAYAN_DATABASE_HOST=127.0.0.1 
        MAYAN_MEDIA_ROOT={{ mayan_dest_dir }}/mayan-edms/media
        /opt/mayan-edms/bin/mayan-edms.py initialsetup

    - name: Mayan collect static files
      become: yes
      become_user: "{{ mayan_user }}"
      shell: >
        MAYAN_MEDIA_ROOT={{ mayan_dest_dir}}/mayan-edms/media
        /opt/mayan-edms/bin/mayan-edms.py collectstatic --noinput


    - name: supervisor - Install mayan app configuration
      template: >
        src=supervisor/mayan.conf.j2
        dest=/etc/supervisor/conf.d/mayan.conf
      when: ansible_distribution == 'Ubuntu'

    # - name: install nginx config
    #   template: >
    #     src=nginx/mayan.conf.j2
    #     dest=/etc/nginx/sites-available/mayan.conf
    
    # - name: enable nginx config
    #   file: >
    #     src=/etc/nginx/sites-available/mayan.conf
    #     dest=/etc/nginx/sites-enabled/mayan.conf
    #     state=link
    #     force=yes
    #   notify: restart nginx

