---
- name: Configure Mayan
  hosts: edms
  become: true
  become_method: sudo
  roles:
    - role: common
    - role: postgres
      postgresql_version: 9.4
  tasks:
    - name: install postgres client dependencies
      apt: >
        pkg=libpq-dev
        state=latest
        update_cache=yes
        cache_valid_time={{ apt_cache_valid_time }}
        force=yes

    - name: create mayan database
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_db: >
        name=mayan
        encoding='UTF-8'
        lc_collate='en_US.UTF-8'
        lc_ctype='en_US.UTF-8'
        template='template0'
      register: mayan_db_create

    - name: create mayan user
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_user: >
        db=mayan
        name=mayan
        password={{ mayan_db_password }}
      when: mayan_db_create.changed

    - name: apply privileges for mayan user
      become: yes
      become_user: "{{ pg_user }}"
      postgresql_privs: >
        db=mayan
        type=schema
        objs=public
        privs=ALL
        roles=mayan
      when: mayan_db_create.changed

